"""Logistic Regression Baseline Fraud Detection

Usage:
  Import directly via the following command:
      from logistic_reg import logreg

Arguments:
  pd_csv:  A csv read through panda
  custom_random_state: Sets random seed for both model and train_test_split
  custom_test_size: Specify test size for split, default .2
  custom_train_size: Specify train size for split, default .8

Options:
  -h, --help  Show this screen.

Returns:
  y_probs: Continuous numeric probability scores generated by log reg for the scaled test set
  y_preds: The predicted numeric labels for fraud/non-fraud generated by log reg for the scaled test set
"""

from pathlib import Path
import logging

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__name__)

#Define LogReg with same parameters as iforestmethod for consistency.
def logreg(pd_csv, custom_random_state=42, custom_test_size=0.2, custom_train_size=0.8):
    
    #Create Features and Labels
    X = pd_csv.drop('Class',axis=1)
    Y = pd_csv['Class']
   
    #Create Train/Test Split, Straatified for Consistent Class Distribution
    X_train, X_test, Y_train, Y_test = train_test_split(X,Y, 
                                  test_size=custom_test_size, 
                                  train_size=custom_train_size, 
                                  random_state=random_state,
                                  stratify=Y) #Stratify for Consistent Class Distribution
    logging.info('Train Test split created...')


    #Scale For Log Reg
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    logging.info('Scaling Xtrain and Xtest...')

    #Create Logistic Regression Model
    log_reg = LogisticRegression(
        random_state = random_state,
        max_iter = 1000,
        class_weight = 'balanced') #Balanced class weight to compensate for underrepresentation of fraud cases
    
    model.fit(X_train_scaled, Y_train)
    logging.info('Model fit on train...')

    return model, scaler #Returns fitted model and scaler objects